name: docker # имя actoins

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: btmc/github-action-docker-build@v1