name: test # имя actoins

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  deploy: # имя джобы
  
    runs-on: ubuntu-latest # операционная система    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3 # клонируем репозиторий
      # устанавливаем питон и зависимости
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: install deps # много сторочный для установки зависимостей
        run: | 
          source venv/bin/activate
          pip install -r requirements.txt

      - name: run jango site
        run: python converter/manage.py test   